import dotenv from 'dotenv';
import sequelize, { testConnection, syncDatabase } from '../lib/sequelize/database.js';
import { User, Product } from '../lib/sequelize/index.js';
import bcrypt from 'bcryptjs';

dotenv.config();

const seedUsers = async () => {
  console.log('🌱 Seeding users...');

  // Create admin user
  await User.create({
    name: 'Admin User',
    email: 'admin@hypemode.com',
    password: 'Admin123!',
    role: 'admin',
    phone: '+1234567890',
    address: '123 Admin Street',
    city: 'New York',
    postalCode: '10001',
    country: 'USA',
  });

  // Create regular user
  await User.create({
    name: 'John Doe',
    email: 'john@example.com',
    password: 'User123!',
    role: 'user',
    phone: '+1234567891',
    address: '456 User Avenue',
    city: 'Los Angeles',
    postalCode: '90001',
    country: 'USA',
  });

  console.log('✅ Users seeded successfully');
};

const seedProducts = async () => {
  console.log('🌱 Seeding products...');

  const products = [
    {
      name: 'Nike Free RN Flyknit Running Shoes – Crimson Red',
      description: 'Step into comfort and style with the Nike Free RN Flyknit. Designed for runners who crave a barefoot-like feel, these lightweight sneakers feature a breathable Flyknit upper that hugs your foot for a snug, sock-like fit. The bold crimson red colorway with a clean white Nike swoosh makes a powerful visual statement, while the flexible Nike Free sole ensures natural movement and superior traction on any surface.',
      price: 89.55,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Shoes',
      subcategory: 'Running',
      sizes: ['38', '39', '40', '41', '42', '43', '44'],
      colors: ['Crimson Red', 'White'],
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 50,
      rating: 4.6,
      reviewsCount: 60,
      featured: true,
      newArrival: true,
      bestSeller: false,
    },
    {
      name: 'Vans Old Skool Classic – Maroon & White',
      description: 'Timeless style meets everyday comfort with the Vans Old Skool Classic in a bold maroon colorway. Crafted with durable canvas and suede upper, this skate-inspired sneaker features the iconic white leather side stripe, a cushioned footbed, and Vans\' signature rubber waffle outsole for maximum grip. Whether you\'re skating, walking, or just chilling, this shoe delivers unmatched street style.',
      price: 91.40,
      originalPrice: 110.00,
      discount: true,
      discountPercentage: 17,
      category: 'Shoes',
      subcategory: 'Sneakers',
      sizes: ['38', '39', '40', '41', '42', '43'],
      colors: ['Maroon', 'White'],
      image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1898&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1898&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 45,
      rating: 4.8,
      reviewsCount: 78,
      featured: true,
      newArrival: false,
      bestSeller: true,
    },
    {
      name: 'Nike Air Force 1 Shadow – Pastel Multicolor',
      description: 'Brighten up your step with the Nike Air Force 1 Shadow in pastel multicolor. This bold reinterpretation of the classic AF1 features layered design elements, playful color blocking in soft pinks, purples, blues, and yellows, and a slightly exaggerated midsole for a modern twist. It\'s the perfect mix of sporty comfort and statement fashion.',
      price: 82.30,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Shoes',
      subcategory: 'Sneakers',
      sizes: ['36', '37', '38', '39', '40', '41'],
      colors: ['Pastel Pink', 'Purple', 'Blue', 'Yellow'],
      image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 30,
      rating: 4.1,
      reviewsCount: 14,
      featured: false,
      newArrival: true,
      bestSeller: false,
    },
    {
      name: 'Nike Air Max Zero – White & Orange Blaze',
      description: 'Stay ahead of the curve with the Nike Air Max Zero, a sleek and modern sneaker that blends lightweight performance with bold style. Featuring a breathable white mesh upper with striking orange overlays and the signature visible Air Max cushioning, this shoe delivers all-day comfort and standout looks. Perfect for everyday wear, workouts, or making a statement on the go.',
      price: 67.79,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Shoes',
      subcategory: 'Sneakers',
      sizes: ['38', '39', '40', '41', '42', '43', '44'],
      colors: ['White', 'Orange'],
      image: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?q=80&w=1625&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?q=80&w=1625&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 60,
      rating: 4.5,
      reviewsCount: 51,
      featured: false,
      newArrival: false,
      bestSeller: true,
    },
    {
      name: 'Yahweh Yireh Black T-Shirt – Minimalist Faith-Inspired Design',
      description: 'Simple, bold, and meaningful. This black t-shirt features the powerful phrase Yahweh Yireh (meaning The Lord Will Provide) in clean, white minimalist typography. Crafted from soft, breathable cotton, it\'s perfect for those who want to wear their faith with subtle style. Whether for daily wear, gatherings, or casual events, this tee brings comfort and inspiration together.',
      price: 18.99,
      originalPrice: 24.99,
      discount: true,
      discountPercentage: 24,
      category: 'T-Shirts',
      subcategory: 'Graphic',
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Black'],
      image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 80,
      rating: 4.6,
      reviewsCount: 64,
      featured: true,
      newArrival: false,
      bestSeller: true,
    },
    {
      name: 'KIKII Original Maneki-Neko Graphic Tee – Beige & Blue',
      description: 'Bring a bold streetwear vibe to your wardrobe with the KIKII™ Original graphic tee. Featuring a playful Maneki-Neko (lucky cat) design in vibrant blue on a beige backdrop, this shirt blends Japanese pop culture with urban attitude. The Japanese text below translates to Believe in God, adding a unique spiritual edge to its aesthetic appeal.',
      price: 35.39,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'T-Shirts',
      subcategory: 'Graphic',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Beige', 'Blue'],
      image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1664&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1664&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 55,
      rating: 4.7,
      reviewsCount: 74,
      featured: true,
      newArrival: true,
      bestSeller: false,
    },
    {
      name: 'Men\'s Linen Blend Short Sleeve Shirt – Light Blue Gray',
      description: 'Embrace effortless style and breathable comfort with this linen-blend short sleeve shirt. Designed with a relaxed fit and a clean, notch neckline, this piece is perfect for warm weather and laid-back days. Its soft light blue-gray tone and natural texture give it a minimalist, earthy vibe—ideal for beach strolls, casual outings, or resort wear.',
      price: 11.99,
      originalPrice: 19.99,
      discount: true,
      discountPercentage: 40,
      category: 'T-Shirts',
      subcategory: 'Casual',
      sizes: ['M', 'L', 'XL', 'XXL'],
      colors: ['Light Blue Gray'],
      image: 'https://images.unsplash.com/photo-1693443688057-85f57b872a3c?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1693443688057-85f57b872a3c?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 70,
      rating: 4.4,
      reviewsCount: 37,
      featured: false,
      newArrival: false,
      bestSeller: true,
    },
    {
      name: 'Grace Chapel To Know Him Vintage Graphic Tee – White',
      description: 'Show your faith with bold style in the Grace Chapel vintage-inspired t-shirt. Featuring a retro eagle and dove graphic on a vibrant orange circle, this tee carries the powerful message: To Know Him & Make Him Known. Made from soft white cotton, it\'s perfect for outdoor events, church groups, or casual wear with purpose.',
      price: 31.99,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'T-Shirts',
      subcategory: 'Graphic',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['White', 'Orange'],
      image: 'https://images.unsplash.com/photo-1714070700742-b59b045d2dd9?q=80&w=1760&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1714070700742-b59b045d2dd9?q=80&w=1760&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 40,
      rating: 4.3,
      reviewsCount: 25,
      featured: false,
      newArrival: true,
      bestSeller: false,
    },
    {
      name: 'Chunky Knit Sweater – Oatmeal Beige',
      description: 'Wrap yourself in warmth and comfort with this cozy chunky knit sweater. Made from a soft, heavyweight yarn, this sweater features a relaxed fit with rolled sleeves and ribbed detailing at the collar, cuffs, and hem. The neutral oatmeal beige tone pairs effortlessly with any outfit, making it a go-to piece for chilly days, layered looks, or casual lounging.',
      price: 88.85,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Sweaters',
      subcategory: 'Knit',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Oatmeal Beige'],
      image: 'https://images.unsplash.com/photo-1631541909061-71e349d1f203?q=80&w=1905&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1631541909061-71e349d1f203?q=80&w=1905&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 35,
      rating: 4.5,
      reviewsCount: 53,
      featured: false,
      newArrival: false,
      bestSeller: true,
    },
    {
      name: 'Cable Knit Sweater – Forest Green',
      description: 'Classic, cozy, and effortlessly stylish — this forest green cable knit sweater is a timeless cold-weather essential. Crafted with thick, textured yarn and a traditional braided cable pattern, it delivers both warmth and elegance. The rich green hue adds a natural, earthy tone that pairs beautifully with jeans, skirts, or layered looks.',
      price: 50.15,
      originalPrice: 65.00,
      discount: true,
      discountPercentage: 23,
      category: 'Sweaters',
      subcategory: 'Knit',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Forest Green'],
      image: 'https://images.unsplash.com/photo-1670603917227-3fd6882dbf97?q=80&w=1635&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1670603917227-3fd6882dbf97?q=80&w=1635&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 50,
      rating: 4.9,
      reviewsCount: 97,
      featured: true,
      newArrival: false,
      bestSeller: true,
    },
    {
      name: 'Minimalist 705. Long Sleeve Tee – Black',
      description: 'Understated and effortlessly cool, the 705. long sleeve tee delivers timeless minimalism with a touch of edge. Made from soft, high-quality cotton, this black shirt features a simple white 705. print at the chest, keeping it sleek, clean, and versatile. Perfect for layering or wearing solo, it\'s a must-have for any modern wardrobe.',
      price: 59.35,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Sweaters',
      subcategory: 'Long Sleeve',
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Black'],
      image: 'https://images.unsplash.com/photo-1618354691551-44de113f0164?q=80&w=1915&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1618354691551-44de113f0164?q=80&w=1915&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 65,
      rating: 4.9,
      reviewsCount: 91,
      featured: true,
      newArrival: true,
      bestSeller: true,
    },
    {
      name: 'Autumn Knit V-Neck Sweater – Chestnut Brown',
      description: 'Embrace the cozy charm of fall with this beautifully textured V-neck sweater in rich chestnut brown. Made with a soft, chunky knit and a relaxed fit, it\'s perfect for layering on crisp autumn days. Whether you\'re sipping cider, snapping film photos, or wandering through golden leaves, this sweater wraps you in warmth and nostalgic style.',
      price: 70.49,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Sweaters',
      subcategory: 'Knit',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Chestnut Brown'],
      image: 'https://images.unsplash.com/photo-1667420265109-58ec49b67021?q=80&w=1664&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1667420265109-58ec49b67021?q=80&w=1664&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 40,
      rating: 4.5,
      reviewsCount: 50,
      featured: false,
      newArrival: false,
      bestSeller: false,
    },
    {
      name: 'Ribbed Turtleneck Sweater Dress – Soft Ivory',
      description: 'Wrap yourself in effortless elegance with this longline ribbed turtleneck sweater in a soft ivory tone. Designed for comfort and sophistication, its extended length and cozy texture make it the perfect hybrid between a sweater and a dress. Whether worn solo or layered with tights and boots, this piece is a winter wardrobe staple.',
      price: 95.88,
      originalPrice: 125.00,
      discount: true,
      discountPercentage: 23,
      category: 'Sweaters',
      subcategory: 'Dress',
      sizes: ['XS', 'S', 'M', 'L'],
      colors: ['Soft Ivory'],
      image: 'https://images.unsplash.com/photo-1687275161342-8699c61e4364?q=80&w=1664&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1687275161342-8699c61e4364?q=80&w=1664&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 25,
      rating: 4.2,
      reviewsCount: 19,
      featured: false,
      newArrival: true,
      bestSeller: false,
    },
    {
      name: 'Pou Nou Kids\' Striped Hedgehog Pocket Sweatshirt – Pink & White',
      description: 'Cuteness meets comfort in this cozy striped sweatshirt for little ones! Featuring a cheerful mama hedgehog design and an attached plush baby hedgehog tucked into a front pocket, this top is as fun to wear as it is to cuddle. Made with soft, breathable fabric and snap buttons at the shoulder for easy dressing, it\'s perfect for playtime, outings, or snuggly days at home.',
      price: 44.40,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Sweaters',
      subcategory: 'Kids',
      sizes: ['2T', '3T', '4T', '5T'],
      colors: ['Pink', 'White'],
      image: 'https://images.unsplash.com/photo-1747752422664-05494f88bf8a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1747752422664-05494f88bf8a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 30,
      rating: 4.4,
      reviewsCount: 40,
      featured: false,
      newArrival: true,
      bestSeller: false,
    },
    {
      name: 'Colorblock Pullover Windbreaker – Grey/Black/White/Yellow',
      description: 'Stay ready for anything with this lightweight colorblock pullover windbreaker. Designed with a bold mix of grey, black, and white on the outside and a striking yellow interior, this jacket combines urban style with outdoor performance. The half-zip front, elastic cuffs, and large front pocket keep it practical, while the bold design makes it pop.',
      price: 63.70,
      originalPrice: 85.00,
      discount: true,
      discountPercentage: 25,
      category: 'Jackets',
      subcategory: 'Windbreaker',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Grey', 'Black', 'White', 'Yellow'],
      image: 'https://images.unsplash.com/photo-1611308725032-74f0a551d018?q=80&w=1622&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1611308725032-74f0a551d018?q=80&w=1622&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 40,
      rating: 4.3,
      reviewsCount: 31,
      featured: false,
      newArrival: false,
      bestSeller: true,
    },
    {
      name: 'Super Puffer Down Jacket – Arctic White',
      description: 'Brave the cold in bold style with the Super Puffer Down Jacket in Arctic White. Engineered for extreme warmth without sacrificing comfort or aesthetics, this high-volume puffer features a sleek, glossy finish, insulated padding, and a high collar with hood for full coverage. The oversized silhouette adds a contemporary edge perfect for streetwear lovers and winter explorers alike.',
      price: 148.49,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Jackets',
      subcategory: 'Puffer',
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Arctic White'],
      image: 'https://images.unsplash.com/photo-1706765779494-2705542ebe74?q=80&w=1651&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1706765779494-2705542ebe74?q=80&w=1651&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 20,
      rating: 4.3,
      reviewsCount: 30,
      featured: true,
      newArrival: true,
      bestSeller: false,
    },
    {
      name: 'Classic Black Faux Leather Biker Jacket – Unisex Fit',
      description: 'Channel timeless rebellion with this black faux leather biker jacket. Featuring an asymmetrical zip, notched lapels, and metallic hardware, this piece delivers instant edge to any outfit. With a smooth matte finish and structured silhouette, it\'s the perfect outer layer for street style, nights out, or everyday boldness.',
      price: 81.59,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Jackets',
      subcategory: 'Leather',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Black'],
      image: 'https://images.unsplash.com/photo-1727515192207-3dc860bfd773?q=80&w=1636&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1727515192207-3dc860bfd773?q=80&w=1636&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 35,
      rating: 4.7,
      reviewsCount: 67,
      featured: true,
      newArrival: false,
      bestSeller: true,
    },
    {
      name: 'Men\'s Sherpa-Lined Bomber Jacket – Navy Blue',
      description: 'Stay warm without sacrificing style in this sherpa-lined bomber jacket. Featuring a timeless navy blue exterior and ultra-soft sherpa interior collar, this winter essential delivers both functionality and comfort. Ribbed cuffs and hem lock in heat, while front button-flap pockets keep your hands cozy and your essentials secure.',
      price: 30.86,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Jackets',
      subcategory: 'Bomber',
      sizes: ['M', 'L', 'XL', 'XXL'],
      colors: ['Navy Blue'],
      image: 'https://images.unsplash.com/photo-1624548140129-74786c5f1279?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1624548140129-74786c5f1279?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 50,
      rating: 4.9,
      reviewsCount: 87,
      featured: false,
      newArrival: false,
      bestSeller: true,
    },
    {
      name: 'Midnight Blue Tuxedo Jacket – Satin Lapel & Pocket Square Detail',
      description: 'Make a striking entrance with this Midnight Blue Tuxedo Jacket, designed for the modern gentleman who appreciates timeless elegance with a bold twist. Featuring a sleek satin shawl lapel, single-button closure, and a patterned inner lining, this jacket blends classic tailoring with rich detail. Finished with a red pocket square and gold-tone chain pin, it\'s a statement piece for black-tie events, weddings, and upscale soirées.',
      price: 48.79,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Jackets',
      subcategory: 'Formal',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Midnight Blue'],
      image: 'https://images.unsplash.com/photo-1667283831517-5b747b3c17c8?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1667283831517-5b747b3c17c8?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 15,
      rating: 4.9,
      reviewsCount: 99,
      featured: true,
      newArrival: true,
      bestSeller: true,
    },
    {
      name: 'Handcrafted Wool Heritage Jacket – Rustic Brown',
      description: 'Timeless, rugged, and full of character, this handcrafted wool jacket blends traditional craftsmanship with enduring warmth. Made from thick, naturally insulating wool, it features contrast black trim, a simple button front, and a visible, hand-stitched aesthetic that evokes mountain village charm and old-world utility. With its subtle blue and orange interior lining details, this piece carries both history and comfort into the modern wardrobe.',
      price: 79.45,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Jackets',
      subcategory: 'Wool',
      sizes: ['M', 'L', 'XL'],
      colors: ['Rustic Brown', 'Black'],
      image: 'https://images.unsplash.com/photo-1649937408746-4d2f603f91c8?q=80&w=1826&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1649937408746-4d2f603f91c8?q=80&w=1826&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 18,
      rating: 4.6,
      reviewsCount: 59,
      featured: false,
      newArrival: false,
      bestSeller: false,
    },
    {
      name: 'Heritage Denim Work Jacket – Raw Indigo with Corduroy Collar',
      description: 'Crafted for durability and style, this Heritage Denim Work Jacket blends classic Americana with utility-driven details. Made from sturdy raw indigo denim, it features reinforced seams, double chest pockets with button flaps, and a standout corduroy collar in warm tobacco brown for added contrast and comfort. Built to last and age beautifully, it\'s a wardrobe staple for transitional weather and everyday wear.',
      price: 97.79,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Jackets',
      subcategory: 'Denim',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Raw Indigo', 'Tobacco Brown'],
      image: 'https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?q=80&w=1869&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?q=80&w=1869&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 28,
      rating: 4.5,
      reviewsCount: 46,
      featured: false,
      newArrival: false,
      bestSeller: true,
    },
    {
      name: 'Tommy Hilfiger Colorblock Puffer Jacket – Black / White / Rust Red',
      description: 'Bold, warm, and unmistakably stylish — this Tommy Hilfiger puffer jacket features a striking tricolor block design in black, white, and rust red. Built for both form and function, it offers insulated warmth, a soft interior lining, and signature branding details on the chest and sleeve. Whether you\'re navigating city streets or heading into the outdoors, this jacket brings classic American style with modern edge.',
      price: 198.29,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Jackets',
      subcategory: 'Puffer',
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Black', 'White', 'Rust Red'],
      image: 'https://images.unsplash.com/photo-1711527124424-463764d8d8e5?q=80&w=1635&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1711527124424-463764d8d8e5?q=80&w=1635&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 22,
      rating: 4.6,
      reviewsCount: 57,
      featured: true,
      newArrival: true,
      bestSeller: false,
    },
    {
      name: 'Ray-Ban Wayfarer Polarized Sunglasses – Classic Black',
      description: 'Timelessly cool and endlessly iconic, the Ray-Ban Wayfarer is the ultimate eyewear essential. This pair features a high-gloss black acetate frame with polarized lenses for superior glare reduction and eye protection. Subtle branding on the arms and lenses ensures authenticity, while the classic shape complements any face and every style.',
      price: 86.19,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Accessories',
      subcategory: 'Sunglasses',
      sizes: ['One Size'],
      colors: ['Black'],
      image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=1760&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=1760&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 60,
      rating: 4.9,
      reviewsCount: 86,
      featured: true,
      newArrival: false,
      bestSeller: true,
    },
    {
      name: 'Clear Frame Retro Sunglasses – Amber Gradient Lenses',
      description: 'Elevate your summer look with these retro-inspired sunglasses featuring a crystal-clear frame and warm amber gradient lenses. Lightweight, effortlessly stylish, and made for sun-drenched days, this pair blends vintage vibes with modern comfort. Whether you\'re lounging by the ocean or strolling through the city, these shades are your go-to for effortless cool.',
      price: 79.57,
      originalPrice: 99.00,
      discount: true,
      discountPercentage: 20,
      category: 'Accessories',
      subcategory: 'Sunglasses',
      sizes: ['One Size'],
      colors: ['Clear', 'Amber'],
      image: 'https://images.unsplash.com/photo-1577803645773-f96470509666?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1577803645773-f96470509666?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 45,
      rating: 4.7,
      reviewsCount: 68,
      featured: false,
      newArrival: true,
      bestSeller: true,
    },
    {
      name: 'Ray-Ban Classic Aviator Sunglasses – Gold Frame / Gradient Lenses',
      description: 'Timeless, bold, and endlessly iconic — the Ray-Ban Aviator redefines cool. With its lightweight gold metal frame and gradient lenses, this legendary design delivers both high performance and signature style. Originally created for pilots, these shades are made for those who live with confidence and clarity.',
      price: 131.89,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Accessories',
      subcategory: 'Sunglasses',
      sizes: ['One Size'],
      colors: ['Gold', 'Gradient'],
      image: 'https://images.unsplash.com/photo-1567473810954-507d59716c25?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1567473810954-507d59716c25?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 40,
      rating: 4.5,
      reviewsCount: 51,
      featured: false,
      newArrival: false,
      bestSeller: true,
    },
    {
      name: 'Gold Rope Chain with Crown Pendant – Ruby Red & CZ Accents',
      description: 'Rule your style with this show-stopping gold rope chain necklace featuring a regal crown pendant. Crafted with a high-polish gold-tone finish, the pendant is adorned with deep ruby-red enamel and shimmering cubic zirconia stones for a look that commands attention. Whether worn solo or layered, this piece adds instant royalty to your jewelry game.',
      price: 127.09,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Accessories',
      subcategory: 'Jewelry',
      sizes: ['One Size'],
      colors: ['Gold', 'Ruby Red'],
      image: 'https://images.unsplash.com/photo-1685970731194-e27b477e87ba?q=80&w=1888&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1685970731194-e27b477e87ba?q=80&w=1888&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 25,
      rating: 4.7,
      reviewsCount: 74,
      featured: true,
      newArrival: true,
      bestSeller: false,
    },
    {
      name: 'Gold Heart Pendant Necklace – Diamond',
      description: 'Elegant and timeless, this gold heart pendant necklace features a delicate diamond accent that catches the light beautifully. Perfect for everyday wear or special occasions, it\'s a classic piece that adds a touch of romance and sophistication to any outfit.',
      price: 184.69,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Accessories',
      subcategory: 'Jewelry',
      sizes: ['One Size'],
      colors: ['Gold'],
      image: 'https://images.unsplash.com/photo-1708220084863-5c249297dd64?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1708220084863-5c249297dd64?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 30,
      rating: 4.9,
      reviewsCount: 96,
      featured: true,
      newArrival: false,
      bestSeller: true,
    },
    {
      name: 'Stainless Steel Curb Chain Necklace – Toggle Clasp Detail',
      description: 'Clean, bold, and unmistakably modern — this stainless steel curb chain necklace is all about sleek sophistication with a twist. Featuring a polished silver-tone finish and a front-facing toggle clasp paired with a statement gemstone accent, it\'s the perfect piece for effortless streetwear flair or elevated casual looks.',
      price: 189.74,
      originalPrice: 240.00,
      discount: true,
      discountPercentage: 21,
      category: 'Accessories',
      subcategory: 'Jewelry',
      sizes: ['One Size'],
      colors: ['Silver'],
      image: 'https://images.unsplash.com/photo-1679973296637-1411c1d25c7e?q=80&w=1665&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1679973296637-1411c1d25c7e?q=80&w=1665&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 20,
      rating: 4.2,
      reviewsCount: 19,
      featured: false,
      newArrival: true,
      bestSeller: false,
    },
    {
      name: 'UrbanTech Slim Backpack – Midnight Black',
      description: 'Designed for the modern commuter, the UrbanTech Slim Backpack delivers minimalist style with maximum functionality. Crafted from durable, water-resistant fabric in a deep midnight black tone, it features a spacious main compartment, padded laptop sleeve, and easy-access front pocket. Whether you\'re heading to class, work, or the airport, this bag keeps your essentials organized and protected in sleek, urban style.',
      price: 76.69,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Accessories',
      subcategory: 'Bags',
      sizes: ['One Size'],
      colors: ['Midnight Black'],
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 50,
      rating: 4.9,
      reviewsCount: 94,
      featured: true,
      newArrival: false,
      bestSeller: true,
    },
    {
      name: 'Woods Summit 55L Hiking Backpack – Forest Green',
      description: 'Conquer the trails with confidence using the Woods Summit 55L Hiking Backpack. Built for serious outdoor enthusiasts, this pack offers a perfect balance of capacity, durability, and comfort. With a weather-resistant forest green shell, reinforced straps, and adjustable support system, it\'s made to handle long treks, unpredictable weather, and tough terrain.',
      price: 74.35,
      originalPrice: null,
      discount: false,
      discountPercentage: null,
      category: 'Accessories',
      subcategory: 'Bags',
      sizes: ['One Size'],
      colors: ['Forest Green'],
      image: 'https://images.unsplash.com/photo-1622260614153-03223fb72052?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      images: ['https://images.unsplash.com/photo-1622260614153-03223fb72052?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
      stock: 35,
      rating: 4.5,
      reviewsCount: 48,
      featured: false,
      newArrival: false,
      bestSeller: true,
    },
  ];

  await Product.bulkCreate(products);

  console.log('✅ Products seeded successfully');
};

const runSeed = async () => {
  try {
    console.log('🚀 Starting database seeding...');

    // Test connection
    const connected = await testConnection();
    if (!connected) {
      console.error('❌ Failed to connect to database');
      process.exit(1);
    }

    // Sync database (WARNING: This will drop all tables and recreate them)
    console.log('⚠️  Syncing database (this will drop existing data)...');
    await syncDatabase(true); // force: true will drop tables

    // Seed data
    await seedUsers();
    await seedProducts();

    console.log('🎉 Database seeding completed successfully!');
    console.log('\n📝 Login credentials:');
    console.log('   Admin: admin@hypemode.com / Admin123!');
    console.log('   User:  john@example.com / User123!');

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

runSeed();

